server: 
  port: 9527
 
spring: 
  application:
    name: springcloud-zuul
 
eureka: 
  client: 
    service-url: 
      defaultZone: http://localhost:7001/eureka
  instance:
    instance-id: zuul-9527
    prefer-ip-address: true 

# http://myzull.com:9527/microservicecloud-dept/dept/get/1
# http://myzull.com:9527/mydept/dept/get/1
zuul:
  #ignored-services: microservicecloud-dept #忽略真实服务名
  # http://myzull.com:9527/atguigu/mydept/dept/get/1
  prefix: /loxn  # 统一的前缀
  ignored-services: "*" #忽略所有服务的真实服务名
  routes: #配置服务名映射
    mydept.serviceId: springcloud-provider-dept
    mydept.path: /mydept/**

