server:
  port: 8002
spring:
   application:
    name: springcloud-provider-dept

eureka:
  client: #客户端注册进eureka服务列表内
    service-url:
      defaultZone: http://localhost:7001/eureka
  instance:
    instance-id: dept-8002.com
    prefer-ip-address: true